---
kind: pipeline
type: docker
name: kube-runner

platform:
  os: linux
  arch: amd64

steps:
  - name: build-for-pr
    image: plugins/docker
    settings:
      repo: reg.cnrancher.com/cnrancher/rancher-exporter
      target: builder
      dry_run: true
    when:
      event:
        - pull_request
    volumes:
      - name: docker
        path: /var/run/docker.sock
  - name: build-for-master
    image: plugins/docker
    settings:
      registry: reg.cnrancher.com
      repo: reg.cnrancher.com/cnrancher/rancher-exporter
      target: runner
      auto_tag: true
      auto_tag_suffix: amd64
      username: 
        from_secret: registry-username
      password: 
        from_secret: registry-password
    when:
      ref:
        - refs/heads/master
        - refs/tags/*
      event:
        - push
        - tag
    volumes:
      - name: docker
        path: /var/run/docker.sock
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock